apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: yahia90/devops:my-finalapp
        imagePullPolicy: Always 
        ports:
        - containerPort: 5002
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: flaskapi-secrets
              key: MYSQL_DATABASE_PASSWORD
        - name: MYSQL_DATABASE_DB
          value:  BucketList
        - name: MYSQL_DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_HOST
      
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
      nodePort: 30100
